
## Assay report

#### Report description

Each row corresponds to an assay in a provided submission. There are several features that can be used to determine if assays are distinct.

So far node frequencies, names and path lengths are included but it would also be good to add degree counts. As previously we calculated in and out degrees for each schema_type node this may be a worthwhile diff parameter to add.

Assay diff parameters

[%header,cols=2*]
|===
|Parameter
|Description

|process_uuid
|Ignored when doing the diff.

|biomaterial_counts
|No. of biomaterial nodes.

|biomaterials
|A distinct list of the specific biomaterial node type.

|process_counts
|No. of process nodes.

|protocol_counts
|No. of protocol nodes.

|protocols
|A distinct list of the specific protocol node types.

|process_to_biomaterial_max
|The longest path length from the assay process node to the furthest biomaterial node.

|process_out_deg
|Out degree of the process node.

|process_in_deg
|In degree of the process node.

|===



#### The query
[source,cypher]
----
MATCH (a:files)-[:DERIVED_FROM]->(p:processes)
WHERE a.specificType IN ['sequence_file', 'image_file']
AND a.submissionID = '{submissionID}'
WITH p
MATCH z=(p)-[:DERIVED_FROM *]->(n:biomaterials)
WITH p, n, z
MATCH (p)-[:DERIVED_FROM *]->(s:processes)
WITH p, n, s, z
ORDER BY n.specificType
MATCH (p)-[*]->(q:protocols)
WITH p, n, s, z, q
ORDER BY q.specificType
RETURN p.uuid AS process_uuid,
count(distinct n) AS biomaterial_counts,
collect(distinct n.specificType) AS biomaterials,
count(distinct s) AS process_counts,
count(distinct q) AS protocol_counts,
collect(distinct q.specificType) AS protocols,
max(length(z)) AS process_to_biomaterial_max,
size((p)-[]->()) as process_out_deg,
size((p)-[]->()) as process_in_deg
----



.A note about all report adocs
[NOTE]
===============================
These cypher queries are designed to generate information to aid reporting and visulaisation of graphs. They should all return dataframes with column headers as feature names and rows for each entity they are reporting for. The granularity of the row information should be clearly described above.
===============================

